/* eslint-disable */
export default async () => {
    const t = {
        ["./shared/domain/base/enums/item-type"]: await import("./shared/domain/base/enums/item-type"),
        ["./modules/counter/domain/enums"]: await import("./modules/counter/domain/enums"),
        ["./modules/counter/domain/order-source"]: await import("./modules/counter/domain/order-source"),
        ["./modules/counter/domain/location"]: await import("./modules/counter/domain/location"),
        ["./modules/counter/domain/commands/place-order.command"]: await import("./modules/counter/domain/commands/place-order.command")
    };
    return { "@nestjs/swagger": { "models": [[import("./modules/counter/application/queries/impl/fulfilled-orders.query"), { "GetFulfilledOrdersQuery": {} }], [import("./modules/counter/domain/commands/place-order.command"), { "CommandItem": { itemType: { required: true, enum: t["./shared/domain/base/enums/item-type"].ItemType } }, "PlaceOrderCommand": { commandType: { required: true, enum: t["./modules/counter/domain/enums"].CommandType }, orderSource: { required: true, enum: t["./modules/counter/domain/order-source"].OrderSource }, location: { required: true, enum: t["./modules/counter/domain/location"].Location }, loyaltyMemberId: { required: true, type: () => String }, baristaItems: { required: true, type: () => [t["./modules/counter/domain/commands/place-order.command"].CommandItem] }, kitchenItems: { required: true, type: () => [t["./modules/counter/domain/commands/place-order.command"].CommandItem] }, createdBy: { required: true, type: () => String } } }], [import("./modules/user/application/queries/impl/login.query"), { "LoginQuery": { username: { required: true, type: () => String }, password: { required: true, type: () => String } } }]], "controllers": [[import("./health.controller"), { "HealthController": { "check": { type: Object } } }], [import("./modules/barista/api/barista.controller"), { "BaristaController": { "get": {} } }], [import("./modules/counter/api/order.controller"), { "OrderController": { "getFulfilledOrders": { type: Object }, "place": {} } }], [import("./modules/kitchen/api/kitchen.controller"), { "KitchenController": { "get": { type: String } } }], [import("./modules/user/api/auth.controller"), { "AuthController": { "login": {} } }]] } };
};